# Use container system
sudo: false

# Cache pip & libsodium
cache:
  directories:
  - $HOME/libsodium
  - $HOME/.cache/pip

# Clean up pip log
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# Build matrix
language: python
matrix:
  include:
  - python: "3.3"
    env: EVENT_LOOP=asyncio
  - python: "3.4"
    env: EVENT_LOOP=asyncio
  - python: "3.5"
    env: EVENT_LOOP=asyncio
  - python: "3.5"
    env: EVENT_LOOP=uvloop
    before_script: "pip install .[uvloop]"

# Install dependencies
before_install:
  - ./.travis-install-libsodium.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/libsodium/lib
install:
  - pip install -U setuptools
  - "pip install .[tests]"
  - pip install codecov

# Run tests
script:
  - py.test --cov-config .coveragerc --cov=saltyrtc --loop=$EVENT_LOOP

# After success
after_success:
  - codecov

