# Use container system
sudo: false

# Build matrix
language: python
matrix:
  include:
  - python: "3.4"
    env: EVENT_LOOP=asyncio
  - python: "3.5"
    env: EVENT_LOOP=asyncio
  - python: "3.5"
    env: EVENT_LOOP=uvloop
    before_script: pip install uvloop

# Install dependencies
before_install:
  - git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure --prefix=${HOME}/libsodium && make && make install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${HOME}/libsodium/lib
  - cd ..
install:
  - pip install .
  - pip install logbook
  - pip install pytest-asyncio pytest-cov
  - pip install codecov

# Run tests
script:
  - echo $LD_LIBRARY_PATH
  - ls -la $HOME/libsodium
  - ls -la $HOME/libsodium/lib
  - py.test --cov-config .coveragerc --cov=saltyrtc --loop=$EVENT_LOOP

# After success
after_success:
  - codecov

